on:
  workflow_dispatch:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SFDX
        run: |
          sudo yarn init
          sudo yarn global add sfdx-cli@latest
          sfdx --version
          sfdx plugins --core
      - name: Install SFDX Scanner
        run: |
          sudo sfdx plugins:install @salesforce/sfdx-scanner
          npm list
          ls -a
          sudo sfdx plugins:link .
          sfdx plugins
      - name: Run SFDX Scanner
        run: |
          sfdx scanner:run --target "force-app/main/default/classes/" --format json --violations-cause-error
