on:
  workflow_dispatch:
jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SFDX
        run: |
          sudo yarn global add sfdx-cli@latest
          sfdx --version
          sfdx plugins --core
      - name: Install SFDX Scanner
        run: |
          echo "y" | sfdx plugins:install @salesforce/sfdx-scanner
          sfdx plugins
      - name: Run SFDX Scanner
        run: |
          sfdx scanner:run --target "force-app/main/default/classes/" --format table --violations-cause-error
