on:
  workflow_dispatch:
jobs:
  validate_sandbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SFDX Client
        run: |
          sudo npm -g install sfdx-cli@latest
          sfdx --version
          sfdx plugins --core
      - name: Authenticate Org
        run: |
          echo "${SANDBOX_JWT_SECRET_KEY}" > ~/server.key
          sfdx force:auth:jwt:grant --clientid ${{ secrets.SANDBOX_CONSUMER_KEY }} --jwtkeyfile ~/server.key --username ${{ secrets.SANDBOX_USERNAME}} -s -a lib --instanceurl "https://libertyits--ghclass.my.salesforce.com"
        env:
          SANDBOX_JWT_SECRET_KEY: ${{ secrets.SANDBOX_JWT_SECRET_KEY }}
          SFDX_AUDIENCE_URL: https://test.salesforce.com
      - name: Check deploy
        run: sfdx force:source:deploy --sourcepath force-app --checkonly -u lib -l RunLocalTests
